name: Testes

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: build setup
              run: |
                  python setup.py build
            - name: Lint with flake8
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: "Create env file"
              run: |
                  touch .env
                  echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
                  echo API_KEY=${{ secrets.API_KEY }} >> .env
                  echo DATABASE_CONNECTION=${{secrets.DATABASE_CONNECTION}} >> .env
                  echo EMAIL_ADDRESS=${{secrets.EMAIL_ADDRESS}} >> .env
                  echo EMAIL_PSW=${{secrets.EMAIL_PSW}} >> .env
                  cat .env
                  
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11"]
        steps:
            - name: Test with pytest
              run: |
                  pytest
